create table plan_it.product
(
    product_id               bigint,
    shorten_code             varchar(20)                                                                not null                                primary key,
    isin_code                varchar(20)                                                                null comment 'ISIN 코드',
    item_name                varchar(100)                                                               null comment '종목명',
    base_date                date                                                                       null comment '기준일자',
    closing_price            int                                                                        null comment '종가',
    difference               int                                                                        null comment '대비(전일 대비 등락가)',
    fluctuation_rate         decimal(20, 3)                                                             null comment '등락률',
    market_open_price        int                                                                        null comment '시가',
    high_price               int                                                                        null comment '고가',
    low_price                int                                                                        null comment '저가',
    trade_quantity           bigint                                                                     null comment '거래량',
    trade_price              bigint                                                                     null comment '거래대금',
    market_total_amount      bigint                                                                     null comment '시가총액',
    stock_listing_count      bigint                                                                     null comment '상장주식수',
    invest_type              enum ('SAFE', 'CONSERVATIVE', 'MODERATE', 'AGGRESSIVE', 'VERY_AGGRESSIVE') null comment '투자 타입',
    created_at               timestamp default CURRENT_TIMESTAMP                                        null,
    updated_at               timestamp default CURRENT_TIMESTAMP                                        null on update CURRENT_TIMESTAMP,
    net_asset_value          decimal(20, 3)                                                             null comment '순자산가치(NAV)',
    base_index_name          varchar(100)                                                               null comment '기초지수명',
    base_index_closing_price decimal(20, 3)                                                             null comment '기초지수 종가',
    net_asset_total_amount   bigint                                                                     null comment '순자산총액',
    expected_return_rate     decimal(5, 2)                                                              null comment '예상 수익률'
);